version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: skyai-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: itheima
      MYSQL_USER: skyai
      MYSQL_PASSWORD: skyai123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

  ollama:
    image: ollama/ollama:latest
    container_name: skyai-ollama
    restart: unless-stopped
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0:11434
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434/api/version"]
      interval: 30s
      timeout: 10s
      retries: 5

  # Optional: Ollama model setup service
  ollama-setup:
    image: ollama/ollama:latest
    container_name: skyai-ollama-setup
    depends_on:
      ollama:
        condition: service_healthy
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_HOST=http://ollama:11434
    entrypoint: >
      /bin/bash -c "
      echo 'Waiting for Ollama server...' &&
      sleep 10 &&
      echo 'Pulling deepseek-r1:1.5b model...' &&
      ollama pull deepseek-r1:1.5b &&
      echo 'Model setup complete!'
      "
    restart: "no"

volumes:
  mysql_data:
    driver: local
  ollama_data:
    driver: local

networks:
  default:
    name: skyai-network